services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: chat-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo
    volumes:
      - chat-db-data:/var/lib/mysql
    command: mysqld --collation-server=utf8mb4_0900_bin --transaction-isolation=READ-COMMITTED
    networks:
      - db-common-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 1

volumes:
  chat-db-data:


networks:
  db-common-network:
    external: true
 